Add type annotation to executor.provider, and consequences (#4130)
The basic point of this PR is to add a type annotation to the provider
attribute of executors.

This brings up 23 type errors, mostly to do with provider sometimes
being optional and sometimes not, with at-distance reasoning about
whether it is optional at any particular point.

This PR addresses them as follows:

1. Resolved by following suggestion and using Sequence in the definition
of cancel and submit - the input list is read only, and sequence is the
correct thing to do there.

```
parsl/executors/status_handling.py:254: error: Argument 1 to "cancel" of "ExecutionProvider" has incompatible type "list[str]"; expected "list[object]"  [arg-type]
parsl/executors/status_handling.py:254: note: "list" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
parsl/executors/status_handling.py:254: note: Consider using "Sequence" instead, which is covariant

parsl/executors/high_throughput/executor.py:881: error: Argument 1 to "cancel" of "ExecutionProvider" has incompatible type "list[str]"; expected "list[object]"  [arg-type]
parsl/executors/high_throughput/executor.py:881: note: "list" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
parsl/executors/high_throughput/executor.py:881: note: Consider using "Sequence" instead, which is covariant
```


2. Strategy/job related type check errors are protected by a check
earlier on if the provider is specified. This PR adds asserts to express
that at-distance reasoning. This PR isn't adding any *new* reasoning. It
is expressing existing reasoning that was not written down.

```
parsl/jobs/error_handlers.py:17: error: Item "None" of "ExecutionProvider | None" has no attribute "init_blocks"  [union-attr]
parsl/executors/status_handling.py:266: error: Item "None" of "ExecutionProvider | None" has no attribute "submit"  [union-attr]
parsl/jobs/strategy.py:156: error: Item "None" of "ExecutionProvider | None" has no attribute "init_blocks"  [union-attr]
parsl/jobs/strategy.py:157: error: Item "None" of "ExecutionProvider | None" has no attribute "init_blocks"  [union-attr]
parsl/jobs/strategy.py:197: error: Item "None" of "ExecutionProvider | None" has no attribute "init_blocks"  [union-attr]
parsl/jobs/strategy.py:198: error: Item "None" of "ExecutionProvider | None" has no attribute "init_blocks"  [union-attr]
parsl/jobs/strategy.py:208: error: Item "None" of "ExecutionProvider | None" has no attribute "min_blocks"  [union-attr]
parsl/jobs/strategy.py:209: error: Item "None" of "ExecutionProvider | None" has no attribute "max_blocks"  [union-attr]
parsl/jobs/strategy.py:212: error: Item "None" of "ExecutionProvider | None" has no attribute "nodes_per_block"  [union-attr]
parsl/jobs/strategy.py:213: error: Item "None" of "ExecutionProvider | None" has no attribute "parallelism"  [union-attr]
```

4. In htex, there is always a provider (because there's a default of
LocalProvider that is used when `None` is supplied as provider), so
assert that fact.

```
parsl/executors/high_throughput/executor.py:303: error: Item "None" of "ExecutionProvider | None" has no attribute "mem_per_node"  [union-attr]
parsl/executors/high_throughput/executor.py:306: error: Item "None" of "ExecutionProvider | None" has no attribute "mem_per_node"  [union-attr]
parsl/executors/high_throughput/executor.py:308: error: Item "None" of "ExecutionProvider | None" has no attribute "cores_per_node"  [union-attr]
parsl/executors/high_throughput/executor.py:309: error: Item "None" of "ExecutionProvider | None" has no attribute "cores_per_node"  [union-attr]
parsl/executors/high_throughput/executor.py:881: error: Item "None" of "ExecutionProvider | None" has no attribute "cancel"  [union-attr]
```

5. These should have been covered by other PR
https://github.com/Parsl/parsl/pull/4129

```
parsl/executors/high_throughput/mpi_executor.py:106: error: Item "ExecutionProvider" of "ExecutionProvider | None" has no attribute "launcher"  [union-attr]
parsl/executors/high_throughput/mpi_executor.py:106: error: Item "None" of "ExecutionProvider | None" has no attribute "launcher"  [union-attr]
```

6. Assert expected setup.

```
parsl/tests/manual_tests/test_worker_count.py:20: error: Item "None" of "ExecutionProvider | None" has no attribute "init_blocks"  [union-attr]
parsl/tests/unit/executors/high_throughput/test_process_worker_pool.py:141: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
parsl/tests/unit/executors/high_throughput/test_process_worker_pool.py:191: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
parsl/tests/test_htex/test_managers_command.py:45: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
parsl/tests/test_htex/test_htex.py:27: error: Item "None" of "ExecutionProvider | None" has no attribute "script_dir"  [union-attr]
parsl/tests/test_htex/mpi/test_bad_mpi_config.py:48: error: Item "ExecutionProvider" of "ExecutionProvider | None" has no attribute "launcher"  [union-attr]
parsl/tests/test_htex/mpi/test_bad_mpi_config.py:48: error: Item "None" of "ExecutionProvider | None" has no attribute "launcher"  [union-attr]
```

# Changed Behaviour

none - many asserts added but they should not be firing (because they're
asserts!)

## Type of change

- Code maintenance/cleanup