Do not pass mutable default to ignore_for_cache (#1656)
* Add CI test for parsl.AUTO_LOGNAME

* Fixing undefined reference to @App with @bash_app. Flake8 issue

* Do not pass mutable default to ignore_for_cache

Fixes #1655.

* Revert "Merge branch 'benc-test-AUTO_LOGNAME' into fresh-ignore-for-cache-1655"

This reverts commit 51f4e6a7631a1cb63eea3a5657f1a2c92d76fee0, reversing
changes made to 2e47f0354fa71788adf85fc63abf73b341b59c0b.

Co-authored-by: Ben Clifford <benc@hawaga.org.uk>
Co-authored-by: Yadu Nand Babuji <yadudoc1729@gmail.com>