Rearrange task message to be an encoded list. It almost looks right if i decode it (see below) but actual unpickling is giving a unicode decode error, and I get the impression that this is some Python2 8-bit binstring that is being interpreted as ASCII rather than as the byte-string it should be interpreted as. So I guess I need to learn a bit more pickle protocol... I think its because the oldish-looking pickle library i'm using in erlang is encoding with BINSTRING when it should be using Python3 BINBYTES? (I should check what i get off the wire from the executor side but I think i should never get a BINSTRING from the executor side: it would be *BINBYTES or *UNICODE for different types?
(this is an argument against reserialisation... that this isn't always clean?)

python3 tmp/p1.py
    0: \x80 PROTO      2
    2: ]    EMPTY_LIST
    3: (    MARK
    4: }        EMPTY_DICT
    5: (        MARK
    6: U            SHORT_BINSTRING 'buffer'
   14: T            BINSTRING  '2016\nC2\n\x80\x04\x95Ò\x07\x00\x00\x00\x00\x00\x00\x8c\ndill._dill\x94\x8c\x10_create_function\x94\x93\x94(h\x00\x8c\x0c_create_code\x94\x93\x94(C\x0e\x04\x02\x08\x02\x0c\x01\x02\x01\x12\x01\x10\x01*ÿ\x94K\x00K\x00K\x00K\x04K\x05K\x1fCn\x95\x01\x97\x00d\x01d\x00l\x00}\x02d\x01d\x02l\x01m\x02}\x03\x01\x00\t\x00\x02\x00\x89\x04|\x00i\x00|\x01¤\x01\x8e\x01S\x00#\x00t\x06\x00\x00\x00\x00\x00\x00\x00\x00$\x00r\x16\x01\x00\x02\x00|\x03|\x02j\t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00«\x00\x00\x00\x00\x00\x00\x00\x8e\x00c\x02Y\x00S\x00w\x00x\x03Y\x00w\x01\x94NK\x00\x8c\x16RemoteExceptionWrapper\x94\x85\x94\x87\x94(\x8c\x03sys\x94\x8c\x10parsl.app.errors\x94h\x07\x8c\tException\x94\x8c\x08exc_info\x94t\x94(\x8c\x04args\x94\x8c\x06kwargs\x94h\nh\x07t\x94\x8c./home/benc/parsl/src/parsl/parsl/app/errors.py\x94\x8c\x07wrapper\x94\x8c\x1bwrap_error.<locals>.wrapper\x94K\x87C>ø\x80\x00ã\x08\x12å\x08;ð\x02\x03\t;Ù\x13\x17\x98\x14Ð\x13(\xa0\x16Ñ\x13(Ð\x0c(øÜ\x0f\x18ò\x00\x01\t;Ù\x13)¨3¯<©<«>Ð\x13:Ò\x0c:ð\x03\x01\t;ú\x94C\x0c\x8d\x07\x15\x00\x95\x1c4\x03³\x014\x03\x94\x8c\x04func\x94\x85\x94)t\x94R\x94}\x94\x8c\x08__name__\x94\x8c\x1aparsl.tests.test_callables\x94s\x8c\x03app\x94Nh\x00\x8c\x0c_create_cell\x94\x93\x94N\x85\x94R\x94\x85\x94t\x94R\x94}\x94\x8c\x0b__wrapped__\x94h\x02(h\x04(C\x02\x02\x02\x94K\x01K\x00K\x00K\x01K\x00K\x03C\x04\x97\x00y\x01\x94N\x88\x86\x94)\x8c\x01x\x94\x85\x94\x8c8/home/benc/parsl/src/parsl/parsl/tests/test_callables.py\x94h\x1eh\x1eK\rC\x05\x80\x00à\x0b\x0f\x94C\x00\x94))t\x94R\x94cparsl.tests.test_callables\n__dict__\nh\x1eNNt\x94R\x94}\x94}\x94\x8c\x0f__annotations__\x94}\x94s\x86\x94bs}\x94h6h7s\x86\x94b\x8c\x08builtins\x94\x8c\x07getattr\x94\x93\x94\x8c\x04dill\x94\x8c\x05_dill\x94\x93\x94\x8c\x08_setattr\x94h;\x8c\x07setattr\x94\x93\x94\x87\x94R\x94h"\x8c\rcell_contents\x94h3\x87\x94R0h\x1b(h\x1ch\x0b\x8c\x07__doc__\x94\x8c\x1aExceptions raised by Apps.\x94\x8c\x0b__package__\x94\x8c\tparsl.app\x94\x8c\n__loader__\x94\x8c\x1a_frozen_importlib_external\x94\x8c\x10SourceFileLoader\x94\x93\x94)\x81\x94}\x94(\x8c\x04name\x94h\x0b\x8c\x04path\x94\x8c./home/benc/parsl/src/parsl/parsl/app/errors.py\x94ub\x8c\x08__spec__\x94\x8c\x11_frozen_importlib\x94\x8c\nModuleSpec\x94\x93\x94)\x81\x94}\x94(hRh\x0b\x8c\x06loader\x94hP\x8c\x06origin\x94hT\x8c\x0cloader_state\x94N\x8c\x1asubmodule_search_locations\x94N\x8c\x19_uninitialized_submodules\x94]\x94\x8c\r_set_fileattr\x94\x88\x8c\x07_cached\x94\x8cG/home/benc/parsl/src/parsl/parsl/app/__pycache__/errors.cpython-312.pyc\x94\x8c\r_initializing\x94\x89ub\x8c\x08__file__\x94hT\x8c\n__cached__\x94hc\x8c\x0c__builtins__\x94cbuiltins\n__dict__\n\x8c\x07logging\x94h\x00\x8c\x0e_import_module\x94\x93\x94hh\x85\x94R\x94\x8c\x05wraps\x94\x8c\tfunctools\x94hm\x93\x94\x8c\rTracebackType\x94h\x00\x8c\n_load_type\x94\x93\x94hp\x85\x94R\x94\x8c\x08Callable\x94\x8c\x06typing\x94hu\x93\x94\x8c\x04List\x94hvhx\x93\x94\x8c\x08Optional\x94hvhz\x93\x94\x8c\x07TypeVar\x94\x8c\x06typing\x94\x8c\x07TypeVar\x94\x93\x94\x8c\x05Union\x94hvh\x80\x93\x94\x8c\tTraceback\x94\x8c\x05tblib\x94h\x82\x93\x94\x8c\tParamSpec\x94\x8c\x11typing_extensions\x94h\x85\x93\x94\x8c\x04File\x94\x8c\x19parsl.data_provider.files\x94h\x88\x93\x94\x8c\nParslError\x94\x8c\x0cparsl.errors\x94h\x8b\x93\x94\x8c\x06logger\x94hh\x8c\tgetLogger\x94\x93\x94h\x0b\x85\x94R\x94\x8c\x0cAppException\x94h\x0bh\x93\x93\x94\x8c\x10AppBadFormatting\x94h\x0bh\x95\x93\x94\x8c\x0fBashExitFailure\x94h\x0bh\x97\x93\x94\x8c\nAppTimeout\x94h\x0bh\x99\x93\x94\x8c\x0fBashAppNoReturn\x94h\x0bh\x9b\x93\x94\x8c\x0eMissingOutputs\x94h\x0bh\x9d\x93\x94\x8c\x10BadStdStreamFile\x94h\x0bh\x9f\x93\x94h\x07h\x0bh\x07\x93\x94\x8c\x01P\x94h\x0bh¢\x93\x94\x8c\x01R\x94h\x0bh¤\x93\x94\x8c\nwrap_error\x94h\x0bh¦\x93\x94u0.19\n01\n\x80\x04\x95\x05\x00\x00\x00\x00\x00\x00\x00K\x00\x85\x94.21\n01\n\x80\x04\x95\x07\x00\x00\x00\x00\x00\x00\x00}\x94}\x94\x86\x94.'
 2086: U            SHORT_BINSTRING 'task_id'
 2095: K            BININT1    1
 2097: u            SETITEMS   (MARK at 5)
 2098: e        APPENDS    (MARK at 3)
 2099: .    STOP
highest protocol among opcodes = 2
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/tmp/p1.py", line 10, in <module>
    pickle.loads(p)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 8: ordinal not in range(128)