Tidy error path through local channel execute_no_wait
Prior to this commit, if an execution was thrown inside the main
part of the body, pid might not have been assigned yet, resulting in
this exception:

> UnboundLocalError: local variable 'pid' referenced before assignment

This commit changes behaviour so that the original exception is
propagated, after logging.