newer mypy.
lots of fiddling

1.

with old mypy:
parsl/executors/high_throughput/mpi_resource_management.py:149: error: "SynchronizedBase[Any]" has no attribute "value"  [attr-defined]

mypy now sees the .value attribute -- ignore[attr-defined] removed in 4 places in mpi_resource_management


2.

with new mypy:
parsl/utils.py:135: error: Statement is unreachable  [unreachable]

this error case is discovered by typeguard==4.4.4 dynamically, which matches the
unreachability diagnosis of mypy. so can be removed.

TODO: should there be a minimum bound on typeguard? this was driven by DESC release versions I think
but probably that was long enough ago to upgrade? I can check recent DESC release?

3. parsl.utils contextlib vs IO[AnyStr] vs IO[Any]

I don't fully understand what the conflict is here now - it seems to have inferred IO[Never] from somewhere

TODO: understand more


in flux:


    dont use or to sequence expressions. mypy gets upset at the const-Noneness

    parsl/executors/flux/executor.py:227: error: "set" of "Event" does not return a value (it only ever returns None)  [func-returns-value]
    parsl/executors/flux/executor.py:227: error: "join" of "Thread" does not return a value (it only ever returns None)  [func-returns-value]