Make executor bad state exception log use the exception
Prior to this, the error message would be reported with no
in-context exception, and so would emit a line like this:

```
2021-11-26 18:21:10.761 parsl.executors.status_handling:111 [ERROR]  Exception:         STDOUT: /home/benc/parsl/src/parsl/runinfo/018/submit_scripts/parsl.localprovider.1637950869.7853742.sh: line 3: executable_that_hopefully_does_not_exist_1030509.py: command not found

NoneType: None
```

The NoneType: None happens there because no exception is in
scope at the moment.

After this change, the log reports:

```
2021-11-26 18:09:51.235 parsl.executors.status_handling:111 [ERROR]  Setting bad state due to exception
Exception:      STDOUT: /home/benc/parsl/src/parsl/runinfo/008/submit_scripts/parsl.localprovider.1637950190.2711153.sh: line 3: executable_that_hopefully_does_not_exist_1030509.py: command not found
```

If the supplied exception object has a stack trace, then that will also be
logged at this point now.