Fix 'import parsl.multiprocessing'
Due to a duplicate parsl.multiprocessing name, one defined in
parsl/__init__.py by `import parsl`, and the other defined by
the module namespace of parsl/multiprocessing.py, behaviour of
imports of parsl.multiprocessing were inconsistent:

>>> from parsl.multiprocessing import MacSafeQueue
>>> MacSafeQueue
<class 'parsl.multiprocessing.MacSafeQueue'>
>>> import parsl.multiprocessing
>>> parsl.multiprocessing.MacSafeQueue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'multiprocessing' has no attribute 'MacSafeQueue'

This PR removes the duplicate definitions of parsl.multiprocessing,
making the intended parsl module exposed in both import cases, and
using a private (_underscored) alias for the internal import in
parsl/__init__.py