Removed connected_workers command channel.
The last/only use of connected_worker/the interchange WORKERS
command was removed in PR #3991.

This PR removes it entirely.

This is part of command channel minimisation project, issue #4133

One manual test was already broken due to out of date API. This PR
does not remove the use of connected_workers in that test. It
continues to be broken due to at least the outdated API, now even
more so.

```
$ python3 parsl/tests/manual_tests/test_memory_limits.py
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/tests/manual_tests/test_memory_limits.py", line 79, in <module>
    x = test_simple(None)
        ^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/tests/manual_tests/test_memory_limits.py", line 23, in test_simple
    HighThroughputExecutor(
TypeError: HighThroughputExecutor.__init__() got an unexpected keyword argument 'suppress_failure'
```