Make process_worker_pool pass mypy (#2052)
* Reverse polarity of mac safe queue imports to satisfy mypy

mypy determines the type of mpQueue by the type of its first usage.

Prior to this commit, that usage was importing MacSafeQueue.
That mean the second import did not type check: what it was importing
was not MacSafeQueue, but Queue.

This commit reverses that, so that mpQueue is now typed as a
Queue, and the subsequent import of MacSafeQueue is acceptable:
MacSafeQueue is a subclass of Queue.

The error message being fixed is this:
parsl/executors/high_throughput/process_worker_pool.py:28: error:
Incompatible import of "mpQueue" (imported name has type "Type[Queue[Any]]",
local name has type "Type[MacSafeQueue]")

* Check process_worker_pool.py in mypy

* Define process_worker_pool logger differently to pass mypy

This defines the global logger variable differently, which appears to pass
mypy checking.

There is still no guarantee that a global 'logger' value has actually been
defined, except when running the process_worker_pool directly as __main__.

Co-authored-by: Zhuozhao Li <zhuozhao@uchicago.edu>