Rework _get_error in simple_error_handler to give more information (#2867)
Before (in pytest output, with htex launch_cmd="/bin/false"):

```
Exception: 	STDOUT: Found cores : 8
Launching worker: 1
```

After:

```
parsl.jobs.errors.TooManyJobFailuresError: Error 1:
	EXIT CODE: 1
	STDOUT: Found cores : 8
Launching worker: 1
```

* Fix counting so it counts even when js.message is None

* Add exit code

* Use a new error subclass rather than Exception

* Pluralise messages in for no-messages string and remove brackets

  '[No error message received]'
    vs
  'No error messages received'