raise an exception when this takes too long, rather than hang...
this is an attempt to address problems similar to #2755 (but not actually #2755) - this patch
addresses the outgoing queue gone away... and causes the task to fail with this stack trace
when trying to submit to an interchange that no longer exists

  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 628, in launch_if_ready
    exec_fu = self.launch_task(task_record)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 720, in launch_task
    exec_fu = executor.submit(executable, task_record['resource_specification'], *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benc/parsl/src/parsl/parsl/executors/high_throughput/executor.py", line 606, in submit
    self.outgoing_q.put(msg)
  File "/home/benc/parsl/src/parsl/parsl/executors/high_throughput/zmq_pipes.py", line 125, in put
    raise RuntimeError("BENC: hit big timeout for pipe put - failing rather than trying forever")
RuntimeError: BENC: hit big timeout for pipe put - failing rather than trying forever