This makes mypy work for python 3.11
This is the error that was occurring.

parsl/providers/base.py:21: error: Incompatible types in assignment (expression has type "int", base class "Enum" defined the type as "Callable[[Enum], Any]")  [assignment]

I would like to understand what changed here in python (vs 3.10)
because it's not clear from the error message and that Callable
signature confuses me.