both tomg and I have seen this sometimes... the two core errors (i'm not sure which one causes which) is that there is thread related connection sharing which is not permitted. (erlang style local connection rather than object-shared connection might help push on that, by removing the opportunity to share connections across threads) and the prepared state - comes from a failed not-rolled-back transaction earlier on.
Perhaps: an error happened. Then tried to do another one. hence the error happened.
then that tried to call rollback, but it was in a different thread (because it was in the sqlalchemy code
which cannot call rollbacks successfully I guess, on broken connections, because we don't know which thread
finalization will happen in)

2020-11-25 12:04:00 parsl.executors.high_throughput.executor:649 [INFO]  Attempting HighThroughputExecutor shutdown
2020-11-25 12:04:00 parsl.executors.high_throughput.executor:651 [INFO]  Finished HighThroughputExecutor shutdown attempt
2020-11-25 12:04:00 parsl.monitoring.monitoring:271 [INFO]  Terminating Monitoring Hub
2020-11-25 12:04:00 parsl.monitoring.monitoring:287 [INFO]  Waiting for Hub to receive all messages and terminate
2020-11-25 12:04:03 parsl.process_loggers:17 [INFO]  exception wrapper: normal ending for thread MainThread in process UNLOGGED
Exception during reset or similar
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 476, in _update
    self.db.update(table=table, columns=columns, messages=messages)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 76, in update
    self.session.bulk_update_mappings(mapper, mappings)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2860, in bulk_update_mappings
    mapper, mappings, True, False, False, False, False
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2876, in _bulk_save_mappings
    transaction = self.begin(subtransactions=True)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 938, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 316, in _begin
    self._assert_active()
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 282, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
    fairy._reset(pool)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 867, in _reset
    pool._dialect.do_rollback(self)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 530, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 46912496695104 and this is thread id 46912630470400.
Exception closing connection <sqlite3.Connection object at 0x2aaab2acc1f0>
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 476, in _update
    self.db.update(table=table, columns=columns, messages=messages)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/parsl/monitoring/db_manager.py", line 76, in update
    self.session.bulk_update_mappings(mapper, mappings)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2860, in bulk_update_mappings
    mapper, mappings, True, False, False, False, False
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2876, in _bulk_save_mappings
    transaction = self.begin(subtransactions=True)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 938, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 316, in _begin
    self._assert_active()
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 282, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 680, in _finalize_fairy
    fairy._reset(pool)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 867, in _reset
    pool._dialect.do_rollback(self)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 530, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 46912496695104 and this is thread id 46912630470400.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/global/homes/d/descdm/.conda/envs/parsl-lsst-dm/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 46912496695104 and this is thread id 46912630470400.
2020-11-25 12:04:03 parsl.process_loggers:17 [INFO]  exception wrapper: normal ending for thread MainThread in process UNLOGGED
2020-11-25 12:04:03 parsl.dataflow.dflow:1055 [INFO]  DFK cleanup complete