Force t.output to str in workqueue error handling
In some situations that I've encountered (working on PR#1181),
t.output is None and so error reporting breaks with:

```
...
  File "/home/benc/parsl/src/parsl/parsl/executors/workqueue/executor.py", line 244, in WorkQueueSubmitThread
    reason += "\nTrace:\n" + t.output
TypeError: Can't convert 'NoneType' object to str implicitly
```