Make sshd channel test errors more obvious
I have repeatedly hit this error:

    def _start_sshd(config_dir: str):
        server_config, priv_key, port = _init_sshd(config_dir)
        sshd_thread = SSHDThread(server_config)
        sshd_thread.start()
        time.sleep(1.0)
        if not sshd_thread.is_alive():
>           raise Exception('Failed to start sshd: {}'.format(sshd_thread.error))
E           Exception: Failed to start sshd: expected str, bytes or os.PathLike object, not NoneType

which does not point clearly to a resolution.

This commit adds in both logging so that pytest --log-cli-level=ERROR will
report stack traces for exceptions such as the above "not NoneType",
and adds an assertion for the common case that is triggering this for me,
which is that sshd cannot be found on the $PATH.

In the case that sshd is not on the $PATH, that error is now reported as:

ERROR    parsl.tests.test_providers.test_local_provider:test_local_provider.py:138 SSHDThread exception from run loop
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/tests/test_providers/test_local_provider.py", line 119, in run
    assert sshpath is not None, "can find sshd executable"
AssertionError: can find sshd executable
assert None is not None