Format BadStateException with the executor label rather than full repr
The full repr for an executor is usually very long and includes all
of the configuration information for that exception, so previously
a BadStateException looked like this, which is awkwardly large:

parsl.executors.errors.BadStateException: Executor HighThroughputExecutor(
    address=None,
    address_probe_timeout=None,
    cores_per_worker=1,
    cpu_affinity='none',
    heartbeat_period=30,
    heartbeat_threshold=120,
    interchange_port_range=(55000, 56000),
    label='htex_local',
    launch_cmd='executable_that_hopefully_does_not_exist_1030509.py',
    managed=True,
    max_workers=1,
    mem_per_worker=None,
    poll_period=1,
    prefetch_capacity=0,
    provider=LocalProvider(
        channel=LocalChannel(
            envs={},
            script_dir='/home/runner/work/parsl/parsl/runinfo/030/submit_scripts',
            userhome='/home/runner/work/parsl/parsl'
        ),
        cmd_timeout=30,
        init_blocks=1,
        launcher=SimpleLauncher(debug=True),
        max_blocks=1,
        min_blocks=0,
        move_files=None,
        nodes_per_block=1,
        parallelism=1,
        worker_init=''
    ),
    storage_access=None,
    worker_debug=True,
    worker_logdir_root=None,
    worker_port_range=(54000, 55000),
    worker_ports=None,
    working_dir=None
) failed due to:        STDERR: /home/runner/work/parsl/parsl/runinfo/030/submit_scripts/parsl.localprovider.1642801165.5067718.sh: line 3: executable_that_hopefully_does_not_exist_1030509.py: command not found

After this commit, the exception instead looks like this:

parsl.executors.errors.BadStateException: Executor htex_local failed due to:    STDERR: /home/benc/parsl/src/parsl/runinfo/000/submit_scripts/parsl.localprovider.1643124620.9775066.sh: line 3: executable_that_hopefully_does_not_exist_1030509.py: command not found