Propagate SLURM submission errors as exceptions, not `None` (#3043)
This PR moves the SLURM provider towards the tighter provider.submit API described in issue #2949 which requires that submission failures are indicated by an exception, rather than by a `None` value.

In this PR, instead of a relatively uninformative `None` value, a richer SubmitException is returned with more information about the submission failure.

I tested this on perlmutter by setting scheduler_options=`#SBATCH --nonsense`.

Before this PR, execution fails with this exception:

```
parsl.executors.errors.BadStateException: Executor PM_HTEX_multinode failed due to: Error 1:
        Failed to start block 0: Executor PM_HTEX_multinode failed to scale due to: Attempt to provision nodes did not return a job ID
```

After this PR, the same failure results in this exception:

```
parsl.executors.errors.BadStateException: Executor PM_HTEX_multinode failed due to: Error 1:
        Failed to start block 0: Cannot launch job parsl.PM_HTEX_multinode.block-0.1706699269.6424484: Could not read job ID from submit command standard output; recode=255, stdout=, stderr=sbatch: unrecognized option '--nonsense'
```

This propagates the `sbatch` error message into the exception stack, hopefully leading the user more directly to their problem.

This PR also adds a retcode parameter to SubmitException, to go alongside the existing stderr and stdout parameters to represent the return state of a unix process.

This PR removes the incorrect docstring that a slurmprovider.submit error occurs because the queue is at capacity - as the above example demostrates, that is not the only cause of a slurmprovider.submit error.

This work comes from the ongoing `benc-mypy` project.