Restrict pandas version used by monitoring
Pandas 1.4, just released, breaks parsl-visualize with this:

ImportError: Pandas requires version '1.4.0' or newer of 'sqlalchemy' (version '1.3.24' currently installed).