Record exclusive parameter for RepresentationMixin
Without this, SlurmProviders cannot be printed at
startup, with the below exception.

  File "./parsl-driver.py", line 26, in <module>
    parsl.load(configuration.parsl_config)
  File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 1021, in load
    cls._dfk = DataFlowKernel(config)
  File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/dataflow/dflow.py", line 82, in __init__
    logger.debug("Starting DataFlowKernel with config\n{}".format(config))
  File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/utils.py", line 211, in __repr__
    if len(assemble_line(args, kwargs)) <= self.__class__.__max_width__:
  File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/utils.py", line 206, in assemble_line
    kwargs = ['{}={}'.format(k, repr(v)) for k, v in sorted(kwargs.items())]
  File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/utils.py", line 206, in <listcomp>
    kwargs = ['{}={}'.format(k, repr(v)) for k, v in sorted(kwargs.items())]
  File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/utils.py", line 211, in __repr__
    if len(assemble_line(args, kwargs)) <= self.__class__.__max_width__:
  File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/utils.py", line 206, in assemble_line
    kwargs = ['{}={}'.format(k, repr(v)) for k, v in sorted(kwargs.items())]
  File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/utils.py", line 206, in <listcomp>
    kwargs = ['{}={}'.format(k, repr(v)) for k, v in sorted(kwargs.items())]
  File "/global/homes/b/bxc/.conda/envs/parsl-imsim-nov2018/lib/python3.6/site-packages/parsl/utils.py", line 187, in __repr__
    raise AttributeError(template.format(self.__class__.__name__, arg))
AttributeError: class SlurmProvider uses exclusive in the constructor, but does not define it as an attribute