Make cores_per_node and mem_per_node regular provider attributes (#3988)
Prior to this PR, these were defined with @property which passed through
directly to underlying state attributes.

Moving from mypy 1.5.1 to 1.18.2 in testing revealed that the type
annotations on the property setters were incorrect. For example,

```
parsl/providers/slurm/slurm.py:174: error: Incompatible types in assignment
(expression has type "int | None", variable has type "int")  [assignment]
```

As part of tidying that up, it seemed to me that those property methods
weren't necessary at all.

This PR removes property behaviour for those attributes. The type
annotations are now defined in ExecutionProvider.__init__ (unchanged as
already correct). The documentation which used to live on the @property
is moved to the class level docstring.

## Type of change

- Code maintenance/cleanup