Fix formatting parameters that mypy has started analyzing harder (#1370)
* Fix formatting parameters that mypy has started analyzing harder

Recent mypy has started checking format parameters harder, resulting in the
following CI failure:

parsl/launchers/launchers.py:118: error: Not all arguments converted during string formatting
parsl/launchers/launchers.py:162: error: Not all arguments converted during string formatting
parsl/launchers/launchers.py:201: error: Not all arguments converted during string formatting

This commit changes those launchers to use a style that mypy and flake8 are both
happy with.

This PR should not change any user facing behaviour.

* fix bug in message in test_basic.py found by newer mypy

* Remove unused formatting of test expected messages

* fixup off-by-one field naming in earlier commit

* remove version pin introduced in #1371